-- CreateTable
CREATE TABLE `TEST` (
    `idTEST` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idTEST`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REPORTE` (
    `idREPORTE` INTEGER NOT NULL AUTO_INCREMENT,
    `Fecha` DATETIME(3) NOT NULL,
    `ASPIRANTE_idAMBIENTE` INTEGER NOT NULL,
    `TEST_idTEST` INTEGER NOT NULL,

    PRIMARY KEY (`idREPORTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
